using BCKash.Domain.Loans;
using Xunit;

namespace BCKash.Domain.Tests.Loans;

/// <summary>
/// The 5 worked examples from docs/interest-calculation-spec.md, verbatim — the acceptance
/// criterion "domain-level unit tests reproduce the exact schedule... for all worked examples,
/// for both interest methods and both amortization methods." These figures were generated by
/// running the implemented algorithm (see the spec doc's header) — this is a best-effort,
/// UNVALIDATED-against-legacy formula; see FR-LN-15's status in FRD.md.
/// </summary>
public class LoanScheduleGeneratorTests
{
    private static readonly DateOnly Start = new(2026, 1, 1);

    private static ScheduleGenerationInput Input(
        decimal principal, decimal rate, InterestRateFrequencyType rateType, int term,
        LoanInterestMethod interestMethod, LoanAmortizationMethod amortizationMethod,
        int graceOnPrincipal = 0, int graceOnInterestCharged = 0, int graceOnInterestPayment = 0) =>
        new(
            Principal: principal, InterestRate: rate, InterestRateType: rateType,
            LoanTerm: term, LoanTermType: FrequencyType.Months,
            RepaymentFrequency: 1, RepaymentFrequencyType: FrequencyType.Months,
            InterestMethod: interestMethod, AmortizationMethod: amortizationMethod,
            CalculationPeriodType: InterestCalculationPeriodType.Same, YearDays: YearDaysType.Days365, MonthDays: MonthDaysType.Days30,
            GraceOnPrincipal: graceOnPrincipal, GraceOnInterestCharged: graceOnInterestCharged, GraceOnInterestPayment: graceOnInterestPayment,
            DisbursementDate: Start);

    [Fact]
    public void Example1_Flat_EqualInstallment_no_grace()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(12000m, 1m, InterestRateFrequencyType.Month, 12, LoanInterestMethod.Flat, LoanAmortizationMethod.EqualInstallment));

        Assert.Equal(12, schedule.Count);
        Assert.All(schedule, i => Assert.Equal(1000m, i.Principal));
        Assert.All(schedule, i => Assert.Equal(120.00m, i.Interest));
        Assert.Equal(12000m, schedule.Sum(i => i.Principal));
        Assert.Equal(1440.00m, schedule.Sum(i => i.Interest));
        Assert.Equal(new DateOnly(2026, 2, 1), schedule[0].DueDate);
        Assert.Equal(new DateOnly(2027, 1, 1), schedule[11].DueDate);
    }

    [Fact]
    public void Example2_Flat_EqualPrincipal_no_grace_matches_EqualInstallment_shape()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(5000m, 2m, InterestRateFrequencyType.Month, 5, LoanInterestMethod.Flat, LoanAmortizationMethod.EqualPrincipal));

        Assert.Equal(5, schedule.Count);
        Assert.All(schedule, i => Assert.Equal(1000m, i.Principal));
        Assert.All(schedule, i => Assert.Equal(100.00m, i.Interest));
        Assert.Equal(5000m, schedule.Sum(i => i.Principal));
        Assert.Equal(500.00m, schedule.Sum(i => i.Interest));
    }

    [Fact]
    public void Example3_DecliningBalance_EqualInstallment_no_grace()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(10000m, 1m, InterestRateFrequencyType.Month, 12, LoanInterestMethod.DecliningBalance, LoanAmortizationMethod.EqualInstallment));

        Assert.Equal(12, schedule.Count);
        Assert.Equal(788.49m, schedule[0].Principal);
        Assert.Equal(100.00m, schedule[0].Interest);
        Assert.Equal(796.37m, schedule[1].Principal);
        Assert.Equal(92.12m, schedule[1].Interest);
        Assert.Equal(879.67m, schedule[11].Principal);
        Assert.Equal(8.80m, schedule[11].Interest);

        // Every installment (except the last, which absorbs the rounding true-up) has the same total.
        for (var i = 0; i < 11; i++)
        {
            Assert.Equal(888.49m, schedule[i].Principal + schedule[i].Interest);
        }

        Assert.Equal(10000.00m, schedule.Sum(i => i.Principal));
        Assert.Equal(661.86m, schedule.Sum(i => i.Interest));
    }

    [Fact]
    public void Example4_DecliningBalance_EqualPrincipal_no_grace()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(6000m, 2m, InterestRateFrequencyType.Month, 6, LoanInterestMethod.DecliningBalance, LoanAmortizationMethod.EqualPrincipal));

        Assert.Equal(6, schedule.Count);
        Assert.All(schedule, i => Assert.Equal(1000m, i.Principal));

        decimal[] expectedInterest = [120.00m, 100.00m, 80.00m, 60.00m, 40.00m, 20.00m];
        for (var i = 0; i < 6; i++)
        {
            Assert.Equal(expectedInterest[i], schedule[i].Interest);
        }

        Assert.Equal(6000m, schedule.Sum(i => i.Principal));
        Assert.Equal(420.00m, schedule.Sum(i => i.Interest));
    }

    [Fact]
    public void Example5_DecliningBalance_EqualInstallment_with_grace_on_principal()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(10000m, 1m, InterestRateFrequencyType.Month, 12, LoanInterestMethod.DecliningBalance, LoanAmortizationMethod.EqualInstallment, graceOnPrincipal: 2));

        Assert.Equal(12, schedule.Count);

        // Grace periods: interest-only, balance untouched.
        Assert.Equal(0m, schedule[0].Principal);
        Assert.Equal(100.00m, schedule[0].Interest);
        Assert.Equal(0m, schedule[1].Principal);
        Assert.Equal(100.00m, schedule[1].Interest);

        // Amortization resumes at period 3, re-computed over the remaining 10 periods.
        Assert.Equal(955.82m, schedule[2].Principal);
        Assert.Equal(100.00m, schedule[2].Interest);
        Assert.Equal(1045.37m, schedule[11].Principal);
        Assert.Equal(10.45m, schedule[11].Interest);

        Assert.Equal(10000.00m, schedule.Sum(i => i.Principal));
        Assert.Equal(758.20m, schedule.Sum(i => i.Interest));
    }

    [Fact]
    public void GraceOnInterestCharged_zeroes_interest_for_the_grace_periods_only()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(12000m, 1m, InterestRateFrequencyType.Month, 12, LoanInterestMethod.Flat, LoanAmortizationMethod.EqualInstallment, graceOnInterestCharged: 2));

        Assert.Equal(0m, schedule[0].Interest);
        Assert.Equal(0m, schedule[1].Interest);
        Assert.All(schedule.Skip(2), i => Assert.Equal(120.00m, i.Interest));

        // Total interest is spread over only the 10 interest-bearing periods, not all 12.
        Assert.Equal(1200.00m, schedule.Sum(i => i.Interest));
    }

    [Fact]
    public void GraceOnInterestPayment_defers_accrued_interest_as_a_lump_sum_without_changing_the_total()
    {
        var schedule = LoanScheduleGenerator.Generate(Input(12000m, 1m, InterestRateFrequencyType.Month, 12, LoanInterestMethod.Flat, LoanAmortizationMethod.EqualInstallment, graceOnInterestPayment: 2));

        Assert.Equal(0m, schedule[0].Interest);
        Assert.Equal(0m, schedule[1].Interest);
        Assert.Equal(360.00m, schedule[2].Interest); // 120 own + 240 deferred from periods 1-2
        Assert.All(schedule.Skip(3), i => Assert.Equal(120.00m, i.Interest));

        // Deferral only shifts timing — the total interest across the schedule is unchanged
        // from the no-grace case (Example 1's 1440.00).
        Assert.Equal(1440.00m, schedule.Sum(i => i.Interest));
    }

    [Fact]
    public void Principal_always_sums_to_exactly_the_disbursed_amount_despite_rounding()
    {
        // A principal/installment-count combination that doesn't divide evenly, to exercise the true-up.
        var schedule = LoanScheduleGenerator.Generate(Input(10000m, 1.75m, InterestRateFrequencyType.Month, 7, LoanInterestMethod.DecliningBalance, LoanAmortizationMethod.EqualPrincipal));

        Assert.Equal(10000m, schedule.Sum(i => i.Principal));
    }
}
